name: Deploy 
on: push
jobs:
 Testing:
  runs-on: ubuntu-latest
  steps:
     - name: Cloning_github_repo
       uses: actions/checkout@v4
     - name: Install node
       uses: actions/setup-node@v4
       with:
        node-version: 18
     - name: Install node modules
       run: |
            npm --version 
            npm ci
     - name: Run npm tests
       run: npm test
 Deployment:
   runs-on: ubuntu-latest
   steps:
     - name: Cloning_github_repo
       uses: actions/checkout@v4
     - name: Install node
       uses: actions/setup-node@v4
       with:
        node-version: 18
     - name: Install node modules
       run: 
            npm ci
     - name: Build the project
       run: npm run build
     - name: Deplpy Project
       run: echo "Deplpying the project"