name: Test_workflow
on: push
jobs:
 Cloning_the_repo:
  runs-on: ubuntu-latest
  steps:
     - name: Cloning_github_repo
       uses: actions/checkout@v4
     - name: Install node
       uses: actions/setup-node@v4
       with:
        node-version: 18
     - name: Install node modules
       run: |
            npm --version 
            npm ci
     - name: Run npm tests
       run: npm test